### ISSUE TITLE
Unnecessary call to `DefaultGenParameters()` in `Map`, `SuchThat`and `DeriveGen`

### ISSUE THREAD

**Issue by talgendler** [leanovate/gopter#29]
Hi,
I'm seeing a performance issue when using generators in somewhat high numbers.
`DefaultGenParameters()` function is calling `rand.New(rand.NewSource(seed))` which internally uses locks among other things in Go. However if one will call `DefaultGenParameters()` once and use this instance instead of repeatedly calling the function it can improve performance dramatically.
In all the examples shown the usage of `DefaultGenParameters()` function is only for the side effect and not the result.

https://github.com/leanovate/gopter/blob/master/derived_gen.go#L109
https://github.com/leanovate/gopter/blob/master/gen.go#L51
https://github.com/leanovate/gopter/blob/master/gen.go#L105

I can create a pull request if needed.

**Comment by untoldwind** [comment]
A PR would be nice, out of the blue I don't know a good example where I coult measure the difference.

**Comment by talgendler** [comment]
@untoldwind Can you please bump the version

**Comment by untoldwind** [comment]
Done. Sorry for the delay
