### ISSUE TITLE
Panic for false preconditions

### ISSUE THREAD

**Issue by jamesd** [leanovate/gopter#3]
Test framework panics on false precondition. Example change to expose the panic can be seen in https://github.com/jamesd/gopter/commit/d411fc1ac2d5a09a52a23380ab98c221e1133388

**Comment by untoldwind** [comment]
Hi,

I just committed a temporary fix for that problem. Unluckily this is just a workaround for a more or less fundamental problem with the gen.Map and gen.FlatMap. I fear its eventually time to refactor them to use reflection instead (there is only so much one can do without generics).

In any case:
It is also necessary to increase the MaxDiscardRatio for this particular examples as the commands generator will produce a lot of empty results with this precondition. Probably I should also add something like a retryUntil as in ScalaCheck, but the Map/FlatMap is more urgent IMHO

**Comment by untoldwind** [comment]
The current HEAD now contains a refactored Map and FlatMap avoiding the underlying problem that caused this issue. There is now also a RetryUntil that is used to generate command lists with preconditions in a quiet efficient way (so the test runs again with default MaxDiscardRatio).

Unluckily the refactoring of Map/FlatMap might break existing code, so I created a tag (v0.1) of the original version.
