### ISSUE TITLE
API tweaks for test reporter

### ISSUE THREAD

**Issue by prateek** [leanovate/gopter#31]
I do a couple of things to work around the default interfaces exposed by `gopter`

(1) I like using `time.Now()` as a seed for my tests, but also having this reported upon failure so I can reproduce the failure. My tests end up looking like:

```
func TestSomethingOrTheOther(t *testing.T) {
	parameters := gopter.DefaultTestParameters()
	seed := time.Now().UnixNano()
	parameters.Rng = rand.New(rand.NewSource(seed))
	properties := gopter.NewProperties(parameters)
...
	properties.Property("...", prop.ForAll(...)
...
	reporter := gopter.NewFormatedReporter(true, 160, os.Stdout)
	if !properties.Run(reporter) {
		t.Errorf("failed with initial seed: %d", seed)
	}
}
```

(2) Overriding width for the formatted reporter
The default test reporter truncates the output to 79 columns (iirc); I've always overriden this to a larger value so that stacktraces do not get chopped into different pieces. 

Would you be open to changing the API (exposing new ctors) to make these the defaults? I'm happy to contribute the changes if so.

**Comment by untoldwind** [comment]
If you have a better/more suitable suggestion for the reporter API I'm happy to integrate the changes

**Comment by prateek** [comment]
@untoldwind created #34 and #35 as proposals.

**Comment by untoldwind** [comment]
I think so ... just reopen it if the issue still persists
