### ISSUE TITLE
Composing generators which require `*gopter.GenParams`

### ISSUE THREAD

**Issue by prateek** [leanovate/gopter#32]
I've got the following situation:

```
// regular generator using gen.* types with gopter.CombineGens/gopter.Map
func genX() gopter.Gen { ... } 

// more complicated generator, which needs the output of `genX`, and the ability
// to use the rng from `*gopter.GenParams`.
func genXY() gopter.Gen {}
```

I can't use any of `Map/FlatMap/MapResult`in `genXY()`, as I still need access to the `*gopter.GenParams`. I ended up doing something hacky like:

```
func genXY() gopter.Gen {
  return func(params *gopter.GenParams) *gopter.GenResult {
    x := genX()(params)
    // using the result of x, especially the shrinkers to create a new result
    // along with the rng from `params`
  }
}
```

This works but causes data races in the rng if I'm using multiple workers. Can we expose a new  API (e.g. `MapExtended(params *gopter.GenParams, result gopter.GenResult)`) to allow for such composition as a first class in the API? 

NB: in an un-related note, thank you so much for this library! My team & I have caught so many issues using it. Massive massive props.

**Comment by untoldwind** [comment]
Actually it should be possible to extend the Map resp. FlatMap functions in this way since they already do a lot of reflection.

Would it help if you have something like this:
```
existingGen.Map(function(value interface{}, params *gopter.GenParms) interface{} {
   return <new value derived from value and params>
})
```

**Comment by prateek** [comment]
@untoldwind Hm only issue with that is access to the `Shrinker` from `existingGen` would be lost. Would you be OK with having another interface that passes it thru too? i.e.

```
existingGen.Map(function(value *gopter.GenResult, params *gopter.GenParms) interface{} {
   return <new value derived from value and params>
})
```

**Comment by untoldwind** [comment]
Yes, I think that should be possible, though the refection code in the "Map" function will be ... messy ;)

I'll give it a try once I have an hour or two to focus.

**Comment by untoldwind** [comment]
The `gen.Map` is now pretty flexible. It accepts any of the following:

```
func (value string) string // string is just an example here
func (value string, params *gopter.GenParameters) string
func (value string) *gopter.GenResult // string is just an example here
func (value string, params *gopter.GenParameters) *gopter.GenResult
func (result *gopter.GenResult) string
func (result *gopter.GenResult, params *gopter.GenParameter) string
func (result *gopter.GenResult) *gopter.GenResult
func (result *gopter.GenResult, params *gopter.GenParameter) *gopter.GenResult
```

which also makes `gen.MapResult` redundant/obsolete.

I think that should cover your case. Just reopen the issue if I missed something.
