### ISSUE TITLE
Add goreportcard link to get listed in awesome-go list

### ISSUE THREAD

**Issue by fkromer** [leanovate/gopter#51]
Do you want to add the badge [![Go Report Card](https://goreportcard.com/badge/github.com/leanovate/gopter)](https://goreportcard.com/report/github.com/leanovate/gopter) from [goreportcard link](https://goreportcard.com/report/github.com/leanovate/gopter) to the README.md to get listed in awesome-go list. For more info refer to this [PR](https://github.com/avelino/awesome-go/pull/2414#issue-259694629).

**Comment by untoldwind** [comment]
Done
