### ISSUE TITLE
Problem Shrinking *time.Time

### ISSUE THREAD

**Issue by anisjonischkeit** [leanovate/gopter#65]
https://github.com/leanovate/gopter/blob/f24d09d1286434cbb67b0f47ebf9c47fdc33cfa9/arbitrary/arbitraries.go#L26

Really sorry about this, turns out I've messed up on the types of the Shrinker. Shrunk values are still `time.Time` rather than `*time.Time`. I'll make some time to fix this up over the next few days.

**Comment by untoldwind** [comment]
I kind of realized the same, because there already is a way to convert a generator to a pointer-generator.

The current version should fix this problem

**Comment by anisjonischkeit** [comment]
Oh nice, had no idea about `gen.PtrOf`.
